services:
  - type: web
    name: kumbh-rakshak-2027
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
